### ISSUE TITLE
How to keep the schema field same order as struct?

### ISSUE THREAD

**Issue by seaguest** [segmentio/parquet-go#119]
Hello,

I have a table already in redshift, I need to keep the same schema (even the order of the fields) to load parquet to redshift.

However I found the library creates the schema based on the struct and sorts the key. what I need is to keep the schema field same order as we defined in struct.

In redshift I have:
```
Schema: message test {
  required binary b (STRING);
  required int32 a (INT(32, true));
  required binary c (STRING);
}
```

The defined struct:
```
	type Test struct {
		B string `parquet:"b,plain,gzip"`
		A string `parquet:"a,plain,gzip"`
		C string `parquet:"c,plain,gzip"`
	}

```

its generated schema:
```
Schema: message Test {
  required binary a (STRING);
  required binary b (STRING);
  required binary c (STRING);
}

```

Is there any way to do that?

**Comment by seaguest** [comment]
I have found the problem, in schema.go
```
func structFieldsOf(t reflect.Type) []reflect.StructField {
  fields := appendStructFields(t, nil, nil)

  for i := range fields {
    f := &fields[i]

    if tag := f.Tag.Get("parquet"); tag != "" {
      name, _ := split(tag)
      if name != "" {
        f.Name = name
      }
    }
  }

  /*  sort.Slice(fields, func(i, j int) bool {
      return fields[i].Name < fields[j].Name
    })
  */
  return fields
}


func (s *structNode) indexOf(name string) int {
  for i, n := range s.names {
    if name == n {
      return i
    }
  }
  return -1

/*
  i := sort.Search(len(s.names), func(i int) bool {
    return s.names[i] >= name
  })
  if i == len(s.names) || s.names[i] != name {
    i = -1
  }
  return i
  */
}

```

the schema names has been ordered for binary search, however in some cases we need to keep the order as we defined in structure, thus we should not order it.

I comment the two section code, then I get the order that I wanted.

**Comment by achille-roussel** [comment]
This is currently done this way "by design", and assumed in many places in the code.

Do you mind explaining what the use case is that requires fields to be in the same order as the Go struct?

**Comment by seaguest** [comment]
@achille-roussel 

we have already tables very big in redshift, and we changed the loaded data format from csv.gz to parquet, thus we need to keep the structure the same as defined in redshift.

I think in some cases we need to keep the order, it would be nice if we can choose not to sort the fields even that would lead some performance loss.

**Comment by achille-roussel** [comment]
The design decision of sorting columns of the schema has been depended upon throughout the code, so it seems like a risky choice to change. That being said, I would be against reviewing and accepting a pull request which makes it possible to retain the order of columns, I just want to warn that it may be a complex change to get right.

Have you considered keeping a mapping externally within the application; I'm probably oversimplifying but I could imagine like having a `map[string]int` which dictates the relationship between the column name and its position in the database may allow the application to do the conversion? I don't have a lot of context on how parquet-go and Redshift interact in your case tho, so please disregard if this is not a good advise.

**Comment by seaguest** [comment]
@achille-roussel 

I just tried to read the parquet file that I wrote with keeping the order, it doesn't work and I come to realize that what you said here.

so the need of keeping struct fields order does exist,  the AWS Redshift load the parquet file based on the fields order not the column name, and what I did (comment sort code) broke the read.

instead of maintaining a map of orders outside the library, I prefer to specifying the order in the annotation, but I am not sure if would be possible, anyway we need a solution for keeping fields in order even if the solution is not perfect.

**Comment by achille-roussel** [comment]
Thanks for the extra details, I see how that's more constraining if Reshift is the limiting factor here. 

If we need to dictate the order of columns in the final file, maybe we can come up with a change which sets the column order at serialization time, even if in memory we continue to use schemas with columns sorted by name, do you think that could work?

**Comment by seaguest** [comment]
yes, I think it should work.

**Comment by achille-roussel** [comment]
Hello @seaguest,

I opened https://github.com/segmentio/parquet-go/pull/140 which relaxes the requirement to sort columns by name in the parquet schema. The column order of structs that the schema is derived from will now be respected, as well as the order of columns in memory when reading parquet files.

If you have time to test it, your feedback will be valuable to understand whether it addresses your original issue.

Let me know!

**Comment by seaguest** [comment]
sorry for my late update.
I tested with the latest code, it does solve the order problem and doesn't need any code change on my side, excellent work!
