### ISSUE TITLE
Is there a way to get the file schema?

### ISSUE THREAD

**Issue by senekis** [segmentio/parquet-go#132]
Currently the File is not exposing the schema in the FileMetaData, to access the schema you need to get it from an specific RowGroup

```go
f, err := os.Open(filename)
if err != nil {
	return nil, err
}
defer f.Close()

s, err := f.Stat()
if err != nil {
	return nil, err
}

p, err := parquet.OpenFile(f, s.Size())
if err != nil {
	return nil, err
}

p.RowGroup(1).Schema()
```

is there a way to get the schema without getting the rowgroup?

**Comment by achille-roussel** [comment]
Hello @senekis, thanks for starting this discussion.

Accessing a row group of the file is currently one way to access the schema.

An alternative could be to construct a schema from the file's root column, for example:
```go
root := file.Root()
schema := parquet.NewSchema(root.Name(), root)
```

I can see how this may not be the simplest path, if you think there is value in adding a method like `parquet.(*File).Schema`, I would be happy to review and merge your contribution.

Let me know if the answer was useful!

**Comment by senekis** [comment]
Hi @achille-roussel,

I think there is value to access the schema through the File since it is weird that you need to build it again, or get it via a row group, since it is part of the footer.

**Comment by achille-roussel** [comment]
Agreed, I opened #142 to add this functionality.
