### ISSUE TITLE
Min/Max values in column index of type []byte

### ISSUE THREAD

**Issue by thorfour** [segmentio/parquet-go#166]
I was looking into using column indicies and noticed that the [format.ColumnIndex](https://github.com/segmentio/parquet-go/blob/0c1b15771dff567aa46967615c98fa322c05cb4d/format/parquet.go#L917) used raw byte slices for the indicies instead of the `parquet.Value` 

Would it make sense to change those to `parquet.Values` to make them easier to utilize?

**Comment by brancz** [comment]
Just had a quick conversation with @achille-roussel, and this is mandated by the thrift definitions, but the layer on top that already exists, does this already: https://github.com/segmentio/parquet-go/blob/35af418766ab7eeba969bb1079506c3eee52f9ba/column_index.go#L9-L33

**Comment by thorfour** [comment]
Great!
