### ISSUE TITLE
Is it possible to read a row into a map[string]interface{} to avoid reflection?

### ISSUE THREAD

**Issue by eatonphil** [segmentio/parquet-go#234]
I build parquet utilities so the schema of the parquet file is not really important to me. If I were to pass in my own struct to the Readerer.Read() function I'd have to use reflection to construct that type and I just want to avoid reflection and guessing at the type as much as possible.

Ideal to me would be something like:

```
row := map[string]interface{}{}
for {
  err = reader.Read(row)
  ...
}
```

Or

```
var row []any
for {
  err = reader.Read(row)
  ...
}
```

And it fills out my map with all the entities rather than filling out a struct. Are either of these possible? I can't tell from skimming the docs/examples.

**Comment by h12w** [comment]
[ReadRows](https://pkg.go.dev/github.com/segmentio/parquet-go#GenericReader.ReadRows) might be what you are looking for.

**Comment by Jeffail** [comment]
@eatonphil I've implemented both a generic decoder and encoder for benthos that you might be able to lift from, it's able to convert back and forth between `parquet.Row` and a generic `map[string]interface{}` structure.

I'd also be happy to contribute these upstream but there's some assumptions around which value types are supported and how they're converted that might not be desirable.

Decoder: https://github.com/benthosdev/benthos/blob/main/internal/impl/parquet/processor_decode.go#L137
Encoder: https://github.com/benthosdev/benthos/blob/main/internal/impl/parquet/processor_encode.go#L239

It needs a bit of a refactor and tidy up as it was mostly written in a hurry but it's not a large footprint so hopefully that helps.

**Comment by achille-roussel** [comment]
Thanks for jumping in @Jeffail 

It seems like the original question was answered, I'm going to close this issue but feel free to reopen if it requires further discussion!
