### ISSUE TITLE
In memory reader

### ISSUE THREAD

**Issue by Arnold1** [segmentio/parquet-go#257]
Hi,

I would like to know if it can read in memory data? is there a way to read it directly into a slice called Foo for example?

```
type Foo struct {
	Id                    int64	`parquet:"name=id, type=INT64"`
	StartDate       int64	`parquet:"name=start_date, type=BYTE_ARRAY"`
	EndDate         int64	`parquet:"name=end_date, type=BYTE_ARRAY"`
}

func readParquetData(content []bytes) ([]*Foo, error) {
	pr, err := NewReader(bytes.NewReader(content))

	u := make([]*Foo, pr.NumRows())
	if err = pr.Read(&u); err != nil {
		return nil, err
	}

       ...
}
```

**Comment by achille-roussel** [comment]
Hello, thanks for reaching out!

The `parquet.GenericReader` and `parquet.Reader` types accept a `io.ReaderAt` as argument. Any type implementing this interface may be used to decode parquet files. For example [`bytes.Reader`](https://pkg.go.dev/bytes#Reader) is an implementation of `io.ReaderAt` backed by a `[]byte`, which may be what you are looking for.

Let me know if the answer was useful!

**Comment by Arnold1** [comment]
hi @achille-roussel do you have an example?
