### ISSUE TITLE
Incorrect memory allocation for boolean ?

### ISSUE THREAD

**Issue by vc42** [segmentio/parquet-go#271]
Let's assume we have PageBufferSize = 64K.  Then the code below will allocate 20MB per each boolean value:

First:
```go
func (c *writerColumn) newColumnBuffer() ColumnBuffer {
	columnBufferCapacity := sort.Search(math.MaxInt32, func(i int) bool {
		return c.columnType.EstimateSize(i) >= int64(c.bufferSize)
	})
```
64Kx8 = 524281

then:
```go
func newOptionalColumnBuffer(base ColumnBuffer, maxDefinitionLevel byte, nullOrdering nullOrdering) *optionalColumnBuffer {
	n := base.Cap()
	return &optionalColumnBuffer{
		base:               base,
		maxDefinitionLevel: maxDefinitionLevel,
		rows:               make([]int32, 0, n),
		definitionLevels:   make([]byte, 0, n),
		nullOrdering:       nullOrdering,
	}
}
```
n =  524281x8 = 4,194,248
 4,194,248x5 bytes = 20MB per boolean column
For 70 boolean columns, memory usage will be 1.4GB and with the default page size of 256K -> 5.6GB

Is the second 8x multiplication a bug ?

**Comment by achille-roussel** [comment]
This does sound like a bug, thanks for reporting!

Let me know if you can submit a fix, otherwise I'll get to it later next week.
