### ISSUE TITLE
occasionally writing 0 bytes to snappy compressed file

### ISSUE THREAD

**Issue by eli-ias** [segmentio/parquet-go#281]
While trying to use this library, I realized that occasionally there are some files being created which are of 0 bytes. Is that an expected behavior or is there something wrong with my implementation? Please take a look at the screenshot below.

<img width="726" alt="Screen Shot 2022-07-25 at 10 20 43 AM" src="https://user-images.githubusercontent.com/91341947/180837178-f68ca339-5891-42f8-af26-f7f70ceee92a.png">

**Comment by Pryz** [comment]
Thanks for opening the issue. I don't think that is expected. Could you share the code you are using to reproduce this behavior ?

**Comment by eli-ias** [comment]
Thank you for the quick response!

It turns out that this may be expected on my end. For another implementation using a different library, a 79 KB file was generated (reduced to 44 KB for the segmentio library). Similarly, I imagine that it is reasonable for a 4 byte file to be reduced to 0 bytes, as shown in the screenshot.

I will close this issue for now, but open another one if I find anything else!
