### ISSUE TITLE
String timestamp

### ISSUE THREAD

**Issue by vc42** [segmentio/parquet-go#288]
We use a string encoded timestamp in a type that's impossible to change.  Here's a possible implementation, not sure if it belongs to the project. If not we'll keep it in our fork:

Data structure:
`type T2 struct {
	Id         int    `parquet:",plain,optional"`
	Name       string `parquet:",plain,optional"`
	Timestamp  string `json:"timestamp,omitempty" parquet:"timestamp,plain,timestamp,optional"`
	Date       string `json:"timestamp,omitempty" parquet:"date,plain,date,optional"`
}
`
E.g.:
`	t := T{
		T1: &T1{
			TA: []*T2{&T2{
				Id:         43,
				Name:       "john",
				Timestamp:  "2022-04-12 19:51:52",
				Date:       "2022-04-12",
			},
			},
		},
	}
`

Implementation:
[diff.dat.gz](https://github.com/segmentio/parquet-go/files/9227372/diff.dat.gz)
[utils.go.gz](https://github.com/segmentio/parquet-go/files/9227374/utils.go.gz)

**Comment by Pryz** [comment]
HI @vc42, not sure what is your issue here. 

Are you expecting the pass a string and have the library converting and ending that string into a int64 ?

**Comment by vc42** [comment]
Yes, we expect to pass a string timestamp/date and have a library convert into int64/int32.  I've attached our implementation in my original message including a simple conversion util library.

**Comment by Pryz** [comment]
I think that's an improvement we would welcome in this library. Feel free to open a PR :)

**Comment by vc42-2** [comment]
Opened a PR.

**Comment by Pryz** [comment]
Closing as per https://github.com/segmentio/parquet-go/pull/295
