### ISSUE TITLE
Occasional crash during garbage collection

### ISSUE THREAD

**Issue by vc42-2** [segmentio/parquet-go#299]
Very rare crashes during GC, hard to reproduce.  Looks like the culprit is sparse/array.go [func (a array) offset(off uintptr) array].  Possibly when "a.ptr == nil" but "off > 0", the GC sees a broken ptr. 

 One possible fix (fix 1):
```diff
--- a/sparse/array.go
+++ b/sparse/array.go
@@ -55,6 +55,18 @@ func (a array) slice(i, j int) array {
 }
 
 func (a array) offset(off uintptr) array {
+       if a.off == 0 {
+               off = 0
+               a.len = 0
+       } else {
+               offsetSize := off / a.off
+               if a.len > offsetSize {
+                       a.len -= offsetSize
+               } else {
+                       off = 0
+                       a.len = 0
+               }
+       }
        return array{
                ptr: unsafe.Add(a.ptr, off),
                len: a.len,
```
Another possible fix (fix 2):
```diff
--- a/sparse/array.go
+++ b/sparse/array.go
@@ -55,6 +55,9 @@ func (a array) slice(i, j int) array {
 }
 
 func (a array) offset(off uintptr) array {
+       if a.ptr == nil {
+               return a
+       }
        return array{
                ptr: unsafe.Add(a.ptr, off),
                len: a.len,
```
Not sure if the "off"argument can apply to the whole array or only the first row.  Depending on that, one can use fix 1 or fix 2.  We use fix 1, and GC related crashes have not been happening  so far.

**Comment by Pryz** [comment]
Hi @vc42-2, thanks for reporting the issue. Can you provide the stack trace of the crash as well please ?

**Comment by vc42-2** [comment]
Pay attention to the following two lines:

runtime: bad pointer in frame github.com/segmentio/parquet-go.writeRowsFuncOfStruct.func2 at 0x401f087740: 0x20
github.com/segmentio/parquet-go.(*optionalColumnBuffer).writeValues(0x40070e4b60, {{0x20?, 0xc000?, 0x2000?}}, {0x0?, 0x60?, 0xbd?})

In "writeValues" the argument "rows" has an incorrect pointer because an offset o 0x20 was added to the nil pointer in the "offset" function.  We got about 5 stack traces (out of about a thousand runs) where the the "bad pointer" message referred to ther "rows.ptr" in "writeValues".
--

Complete stack:

runtime: bad pointer in frame github.com/segmentio/parquet-go.writeRowsFuncOfStruct.func2 at 0x401f087740: 0x20
fatal error: invalid pointer found on stack
runtime stack:
runtime.throw({0xed31e2?, 0x1a5a3e0?})
	/usr/local/go/src/runtime/panic.go:992 +0x50 fp=0x400008b630 sp=0x400008b600 pc=0x43970
runtime.adjustpointers(0x400008b9d0?, 0x26dc73?, 0x172a11b?, {0x1a0de90?, 0x1a5a3e0?})
	/usr/local/go/src/runtime/stack.go:628 +0x1b8 fp=0x400008b670 sp=0x400008b630 pc=0x5c528
runtime.adjustframe(0x400008b9d0, 0x400008bac8)
	/usr/local/go/src/runtime/stack.go:670 +0xa4 fp=0x400008b700 sp=0x400008b670 pc=0x5c604
runtime.gentraceback(0x2000?, 0x0?, 0x0?, 0x40000021a0, 0x0, 0x0, 0x7fffffff, 0xf37a30, 0xbbdf40?, 0x0)
	/usr/local/go/src/runtime/traceback.go:334 +0x794 fp=0x400008ba30 sp=0x400008b700 pc=0x66e74
runtime.copystack(0x40000021a0, 0x2000)
	/usr/local/go/src/runtime/stack.go:930 +0x300 fp=0x400008bbf0 sp=0x400008ba30 pc=0x5cdf0
runtime.shrinkstack(0x40000021a0)
	/usr/local/go/src/runtime/stack.go:1212 +0x124 fp=0x400008bc10 sp=0x400008bbf0 pc=0x5d9c4
runtime.scanstack(0x40000021a0, 0x4000058638)
	/usr/local/go/src/runtime/mgcmark.go:754 +0xc0 fp=0x400008be20 sp=0x400008bc10 pc=0x2d7a0
runtime.markroot.func1()
	/usr/local/go/src/runtime/mgcmark.go:241 +0xb8 fp=0x400008be70 sp=0x400008be20 pc=0x2c6e8
runtime.markroot(0x4000058638, 0x84, 0x1)
	/usr/local/go/src/runtime/mgcmark.go:214 +0x1fc fp=0x400008bf10 sp=0x400008be70 pc=0x2c39c
runtime.gcDrain(0x4000058638, 0x7)
	/usr/local/go/src/runtime/mgcmark.go:1047 +0x420 fp=0x400008bf70 sp=0x400008bf10 pc=0x2e350
runtime.gcBgMarkWorker.func2()
	/usr/local/go/src/runtime/mgc.go:1295 +0x6c fp=0x400008bfc0 sp=0x400008bf70 pc=0x2af3c
runtime.systemstack()
	/usr/local/go/src/runtime/asm_arm64.s:241 +0x6c fp=0x400008bfd0 sp=0x400008bfc0 pc=0x715bc
goroutine 69 [GC worker (idle)]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm64.s:198 +0x8 fp=0x4000608740 sp=0x4000608730 pc=0x71538
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1263 +0x1dc fp=0x40006087d0 sp=0x4000608740 pc=0x2ac1c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x40006087d0 sp=0x40006087d0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 1 [GC assist marking (scan)]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_arm64.s:198 +0x8 fp=0x401f087390 sp=0x401f087380 pc=0x71538
runtime.gcAssistAlloc(0x40000021a0)
	/usr/local/go/src/runtime/mgcmark.go:468 +0x1c4 fp=0x401f0873f0 sp=0x401f087390 pc=0x2ce24
runtime.mallocgc(0x2a80, 0x0, 0x0)
	/usr/local/go/src/runtime/malloc.go:973 +0x140 fp=0x401f087460 sp=0x401f0873f0 pc=0x1c270
runtime.growslice(0x101000000000003?, {0x400897c000?, 0x6?, 0xc000?}, 0x400fb09558?)
	/usr/local/go/src/runtime/slice.go:272 +0x408 fp=0x401f0874c0 sp=0x401f087460 pc=0x5b438
github.com/segmentio/parquet-go.(*optionalColumnBuffer).writeValues(0x40070e4b60, {{0x20?, 0xc000?, 0x2000?}}, {0x0?, 0x60?, 0xbd?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220724172517-a6782fd01417/column_buffer.go:340 +0x110 fp=0x401f087580 sp=0x401f0874c0 pc=0xb35f90
github.com/segmentio/parquet-go.writeRowsFuncOfRequired.func1({0x4000d76000, 0x381, 0x0?}, {{0x20?, 0x40002d6e90?, 0xc0?}}, {0xc8?, 0x96?, 0xb0?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220724172517-a6782fd01417/column_buffer_go18.go:96 +0x148 fp=0x401f087610 sp=0x401f087580 pc=0xb41ac8
github.com/segmentio/parquet-go.writeRowsFuncOfOptional.func1({0x4000d76000?, 0x0?, 0xc665e0?}, {{0x20?, 0x10?, 0x1b52b88?}}, {0xc8?, 0x97?, 0xb0?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220724172517-a6782fd01417/column_buffer_go18.go:105 +0xf0 fp=0x401f0876d0 sp=0x401f087610 pc=0xb41e00
github.com/segmentio/parquet-go.writeRowsFuncOfStruct.func2({0x4000d76000, 0x381, 0x381}, {{0x20?, 0xd0?, 0x4000c9ae10?}}, {0x38?, 0xe1?, 0xbf?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220724172517-a6782fd01417/column_buffer_go18.go:331 +0xcc fp=0x401f087750 sp=0x401f0876d0 pc=0xb42e3c
github.com/segmentio/parquet-go.writeRowsFuncOfPointer.func2({0x4000d76000?, 0x381?, 0x381?}, {{0x20?, 0x4000ce6000?, 0x401be61e16?}}, {0x0?, 0x0?, 0x1?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220724172517-a6782fd01417/column_buffer_go18.go:232 +0x6c fp=0x401f0877d0 sp=0x401f087750 pc=0xb4242c
github.com/segmentio/parquet-go.writeRowsFuncOfStruct.func2({0x4000d76000, 0x381, 0x381}, {{0x0?, 0x180?, 0x4000864030?}}, {0x38?, 0xe1?, 0xbf?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220724172517-a6782fd01417/column_buffer_go18.go:331 +0xcc fp=0x401f087850 sp=0x401f0877d0 pc=0xb42e3c
github.com/segmentio/parquet-go.writeRowsFuncOfPointer.func2({0x4000d76000, 0x381, 0x381}, {{0x4000ce6050?, 0x0?, 0x401be613af?}}, {0x0?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220724172517-a6782fd01417/column_buffer_go18.go:243 +0xec fp=0x401f0878d0 sp=0x401f087850 pc=0xb424ac
github.com/segmentio/parquet-go.writeRowsFuncOfStruct.func2({0x4000d76000, 0x381, 0x381}, {{0x4000ce6000?, 0x0?, 0x0?}}, {0x0?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220724172517-a6782fd01417/column_buffer_go18.go:331 +0xcc fp=0x401f087950 sp=0x401f0878d0 pc=0xb42e3c
github.com/segmentio/parquet-go.makeWriteFunc[...].func1({0x4000ce6000?, 0xa?, 0x1})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220724172517-a6782fd01417/writer_go18.go:121 +0x104 fp=0x401f0879e0 sp=0x401f087950 pc=0xb9ca84
github.com/segmentio/parquet-go.(*GenericWriter[...]).Write(0x4000cc3380?, {0x4000ce6000, 0x0?, 0x0?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220724172517-a6782fd01417/writer_go18.go:142 +0x40 fp=0x401f087a40 sp=0x401f0879e0 pc=0xb9cc20
github.vianttech.com/etl/adelphic_logs/parquet.Transcode.func2({0x40000401e0?, 0x401be5b000?}, {0x40006f663c?, 0x40002d5ec0?, 0x40006bfc48?}, 0x0?, {0x4000ce6000?, 0x0?, 0x40006bfb68?}, 0x400fb09b70, ...)
	/go/pkg/mod/github.vianttech.com/etl/adelphic_logs@v0.0.0-20220803223014-75ccec969ea9/parquet/transcoder18.go:98 +0x94 fp=0x401f087ae0 sp=0x401f087a40 pc=0xb9c594
github.vianttech.com/etl/adelphic_logs/parquet.Transcode({0x1211af0, 0x4000116000}, 0xf36228, {0x40000401e0, 0x42}, {0x40001cc0a0, 0x9d}, 0xf36250, {0x0, 0x0}, ...)
	/go/pkg/mod/github.vianttech.com/etl/adelphic_logs@v0.0.0-20220803223014-75ccec969ea9/parquet/transcoder18.go:105 +0x654 fp=0x401f087dd0 sp=0x401f087ae0 pc=0xb9bf04
github.vianttech.com/etl/adelphic_logs/parquet.TranscodeNoBidEvent({0x1211af0?, 0x4000116000?}, {0x40000401e0?, 0x1c5c4?}, {0x40001cc0a0?, 0xa?}, {0x0?, 0x0?}, {0x120d610?, 0x40002d5ec0?})
	/go/pkg/mod/github.vianttech.com/etl/adelphic_logs@v0.0.0-20220803223014-75ccec969ea9/parquet/nobid.go:10 +0x7c fp=0x401f087e50 sp=0x401f087dd0 pc=0xb9b83c
main.main()
	/go/src/github.vianttech.com/etl/app/transcoder/nobid/nobid_uploader.go:41 +0x510 fp=0x401f087f70 sp=0x401f087e50 pc=0xbbdf40
runtime.main()
	/usr/local/go/src/runtime/proc.go:250 +0x258 fp=0x401f087fd0 sp=0x401f087f70 pc=0x45f48
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x401f087fd0 sp=0x401f087fd0 pc=0x73b44
goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x400007cfa0 sp=0x400007cf80 pc=0x46328
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:367
runtime.forcegchelper()
	/usr/local/go/src/runtime/proc.go:301 +0xb8 fp=0x400007cfd0 sp=0x400007cfa0 pc=0x461b8
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x400007cfd0 sp=0x400007cfd0 pc=0x73b44
created by runtime.init.6
	/usr/local/go/src/runtime/proc.go:289 +0x28
goroutine 3 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x400007d770 sp=0x400007d750 pc=0x46328
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:367
runtime.bgsweep(0x0?)
	/usr/local/go/src/runtime/mgcsweep.go:297 +0x110 fp=0x400007d7b0 sp=0x400007d770 pc=0x32f30
runtime.gcenable.func1()
	/usr/local/go/src/runtime/mgc.go:177 +0x2c fp=0x400007d7d0 sp=0x400007d7b0 pc=0x2868c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x400007d7d0 sp=0x400007d7d0 pc=0x73b44
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:177 +0x74
goroutine 4 [GC scavenge wait]:
runtime.gopark(0xfc9b610ad51be?, 0x10000?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x400007df00 sp=0x400007dee0 pc=0x46328
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:367
runtime.bgscavenge(0x0?)
	/usr/local/go/src/runtime/mgcscavenge.go:364 +0x2b0 fp=0x400007dfb0 sp=0x400007df00 pc=0x30eb0
runtime.gcenable.func2()
	/usr/local/go/src/runtime/mgc.go:178 +0x2c fp=0x400007dfd0 sp=0x400007dfb0 pc=0x2862c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x400007dfd0 sp=0x400007dfd0 pc=0x73b44
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:178 +0xb8
goroutine 17 [finalizer wait]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000078590 sp=0x4000078570 pc=0x46328
runtime.goparkunlock(...)
	/usr/local/go/src/runtime/proc.go:367
runtime.runfinq()
	/usr/local/go/src/runtime/mfinal.go:177 +0xd4 fp=0x40000787d0 sp=0x4000078590 pc=0x27824
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x40000787d0 sp=0x40000787d0 pc=0x73b44
created by runtime.createfing
	/usr/local/go/src/runtime/mfinal.go:157 +0x9c
goroutine 18 [select]:
runtime.gopark(0x4000078f78?, 0x3?, 0x0?, 0x0?, 0x4000078f62?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000078e10 sp=0x4000078df0 pc=0x46328
runtime.selectgo(0x4000078f78, 0x4000078f5c, 0x400020c100?, 0x0, 0x0?, 0x1)
	/usr/local/go/src/runtime/select.go:328 +0x6bc fp=0x4000078f20 sp=0x4000078e10 pc=0x5633c
go.opencensus.io/stats/view.(*worker).start(0x400020c100)
	/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0x88 fp=0x4000078fb0 sp=0x4000078f20 pc=0x4b6358
go.opencensus.io/stats/view.init.0.func1()
	/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x2c fp=0x4000078fd0 sp=0x4000078fb0 pc=0x4b567c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x4000078fd0 sp=0x4000078fd0 pc=0x73b44
created by go.opencensus.io/stats/view.init.0
	/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0xa8
goroutine 33 [GC worker (idle)]:
runtime.gopark(0x4000079788?, 0x422b6c?, 0x11?, 0x0?, 0x8?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000079740 sp=0x4000079720 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x40000797d0 sp=0x4000079740 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x40000797d0 sp=0x40000797d0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 5 [GC worker (idle)]:
runtime.gopark(0x0?, 0x2?, 0x80?, 0xa3?, 0x400009c000?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x400007c740 sp=0x400007c720 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x400007c7d0 sp=0x400007c740 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x400007c7d0 sp=0x400007c7d0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 20 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000079f40 sp=0x4000079f20 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x4000079fd0 sp=0x4000079f40 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x4000079fd0 sp=0x4000079fd0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 34 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000548740 sp=0x4000548720 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x40005487d0 sp=0x4000548740 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x40005487d0 sp=0x40005487d0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 49 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000544740 sp=0x4000544720 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x40005447d0 sp=0x4000544740 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x40005447d0 sp=0x40005447d0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 65 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000606740 sp=0x4000606720 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x40006067d0 sp=0x4000606740 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x40006067d0 sp=0x40006067d0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 50 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000544f40 sp=0x4000544f20 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x4000544fd0 sp=0x4000544f40 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x4000544fd0 sp=0x4000544fd0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 21 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x400007a740 sp=0x400007a720 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x400007a7d0 sp=0x400007a740 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x400007a7d0 sp=0x400007a7d0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 51 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000545740 sp=0x4000545720 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x40005457d0 sp=0x4000545740 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x40005457d0 sp=0x40005457d0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 35 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000548f40 sp=0x4000548f20 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x4000548fd0 sp=0x4000548f40 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x4000548fd0 sp=0x4000548fd0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 66 [GC worker (idle)]:
runtime.gopark(0x1b54240?, 0x3?, 0xd9?, 0x59?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000606f40 sp=0x4000606f20 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x4000606fd0 sp=0x4000606f40 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x4000606fd0 sp=0x4000606fd0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 22 [GC worker (idle)]:
runtime.gopark(0x1b54240?, 0x1?, 0x9b?, 0x90?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x400007af40 sp=0x400007af20 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x400007afd0 sp=0x400007af40 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x400007afd0 sp=0x400007afd0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 52 [GC worker (idle)]:
runtime.gopark(0x1b54240?, 0x1?, 0x5d?, 0x33?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000545f40 sp=0x4000545f20 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x4000545fd0 sp=0x4000545f40 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x4000545fd0 sp=0x4000545fd0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 67 [GC worker (idle)]:
runtime.gopark(0x1b54240?, 0x3?, 0xec?, 0x92?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000607740 sp=0x4000607720 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x40006077d0 sp=0x4000607740 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x40006077d0 sp=0x40006077d0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c
goroutine 68 [GC worker (idle)]:
runtime.gopark(0x1b54240?, 0x1?, 0xb0?, 0x96?, 0x0?)
	/usr/local/go/src/runtime/proc.go:361 +0xe8 fp=0x4000607f40 sp=0x4000607f20 pc=0x46328
runtime.gcBgMarkWorker()
	/usr/local/go/src/runtime/mgc.go:1207 +0xec fp=0x4000607fd0 sp=0x4000607f40 pc=0x2ab2c
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm64.s:1263 +0x4 fp=0x4000607fd0 sp=0x4000607fd0 pc=0x73b44
created by runtime.gcBgMarkStartWorkers
	/usr/local/go/src/runtime/mgc.go:1131 +0x2c

**Comment by vc42-2** [comment]
Alternatively, you can check for a nil pointer in this function (i.e. do not apply Offset if rows.ptr is nil):	

return func(buffers []ColumnBuffer, rows sparse.Array, levels columnLevels) error {
		for _, column := range columns {
			if err := column.writeRows(buffers, rows.Offset(column.offset), levels); err != nil {
				return err
			}
		}
		return nil
	}

**Comment by joe-elliott** [comment]
We have been testing performance improvements in GenericWriter vs. Writer. I believe we have recently seen the same issue. It occurred while using the GenericWriter, but we have never seen this using the normal Writer despite writing billions of rows with it.

[logs.txt](https://github.com/segmentio/parquet-go/files/9353936/logs.txt)

**Comment by vc42-2** [comment]
I do not believe rows.Offset(column.offset) is used in the old style code.
