### ISSUE TITLE
GenericWriter doesn't support maps

### ISSUE THREAD

**Issue by Pryz** [segmentio/parquet-go#302]
The current implementation of the GenericWriter doesn't support the usage of maps within a schema.

Example:
```
type Span struct {
  ...
  Attributes map[string]json.RawMesssage
}
```

will panic with ```panic: cannot convert Go values of type map[string]json.RawMessage to parquet value```

**Comment by achille-roussel** [comment]
Do you have a code snippet and full stack trace to share?

**Comment by Pryz** [comment]
Opened https://github.com/segmentio/parquet-go/pull/313 turns out the issue was not what I was thinking about.
