### ISSUE TITLE
Error converting rows with repeated groups

### ISSUE THREAD

**Issue by zolstein-clumio** [segmentio/parquet-go#308]
When parsing a file with repeated groups, if the read schema does not _exactly_ match the file schema, the reader fails to parse the file. This seems to happen because when `(*convertRows).ReadRows` converts values between the source and target column, it implicitly sorts the row by column index, but `(*Schema).Reconstruct` expects the columns of repeated nested groups to have their fields interleaved by sub-object.

This problem occurs whether adding or removing a field in the read schema.

Sample test-case:
```go
func TestConvertNested(t *testing.T) {
	type Nested struct {
		N1 int64
		N2 int64
	}
	type WriteStruct struct {
		F1 int64
		F2 []Nested
	}
	type ReadStruct struct {
		F2 []Nested
	}
	var buf bytes.Buffer
	err := parquet.Write[WriteStruct](&buf, []WriteStruct{
		{F1: 1, F2: []Nested{{1, 2}, {3, 4}}},
	})
	if err != nil {
		t.Fatal(err)
	}
	rows, err := parquet.Read[ReadStruct](bytes.NewReader(buf.Bytes()), int64(buf.Len()))
	if err != nil {
		// Fails here with: F2 → N2 → no values found in parquet row for column 1
		t.Fatal(err)
	}
	require.Equal(t, []ReadStruct{{[]Nested{{1, 2}, {3, 4}}}}, rows)
}
```

**Comment by achille-roussel** [comment]
This might be related to #250
