### ISSUE TITLE
Pages definitions/repetition levels buffer pools not reused.

### ISSUE THREAD

**Issue by cyriltovena** [segmentio/parquet-go#326]
It seems that when trying to return the buffer pool for both [definitions levels and repetitions levels](https://github.com/segmentio/parquet-go/blob/main/column.go#L581)  it won't actually work since when building the related page (mostly Repeated/Optional), it creates a [bufferRef](https://github.com/segmentio/parquet-go/blob/main/column.go#L645-L656) which adds to the total count of ref for the respective buffer pools but never release it.

Not sure if this is normal but it seems to me that those buffer could be reused between pages.
This seems a good idea to improve performance for parquet files with a lot of pages taking advantage of nested/repeated elements.

I wasn't able to find a good way forward but I was also wondering if we care at all.

**Comment by cyriltovena** [comment]
Ok it seems that https://github.com/segmentio/parquet-go/pull/330 closes this right @achille-roussel

**Comment by achille-roussel** [comment]
Thanks for reporting and following up!
