### ISSUE TITLE
Panic (nil dereference) when writing to GenericBuffer[any] without schema

### ISSUE THREAD

**Issue by BlakeOrth** [segmentio/parquet-go#347]
As the title states, the library panics with a nil pointer dereference when attempting to write to a `GenericBuffer[any]` if no schema is provided. 

```
# ./parquet_panic 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x6cf160]

goroutine 1 [running]:
github.com/segmentio/parquet-go.(*Schema).Deconstruct(0x0, {0x0?, 0x0, 0x0}, {0x71bd00?, 0xc0001191b0?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220914222423-67dbe8d21ca5/schema.go:231 +0x120
github.com/segmentio/parquet-go.(*GenericBuffer[...]).writeRows(0xc000122090, {0xc0001191b0, 0x1, 0x0})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220914222423-67dbe8d21ca5/buffer_go18.go:154 +0x1b2
github.com/segmentio/parquet-go.(*GenericBuffer[...]).Write(0x0?, {0xc0001191b0?, 0x0?, 0x721c60?})
	/go/pkg/mod/github.com/segmentio/parquet-go@v0.0.0-20220914222423-67dbe8d21ca5/buffer_go18.go:125 +0x47
main.main()
	/parquet_panic/main.go:14 +0x91
```

Minimal reproduction code:
```go
package main

import (
	parquet "github.com/segmentio/parquet-go"
)

type TestType struct{}

func main() {
	buffer := parquet.NewGenericBuffer[any]()

	data := make([]any, 1)
	data[0] = TestType{}
	_, _ = buffer.Write(data)
}
```

**Comment by abraithwaite** [comment]
Digging deeper into this issue, I'm not sure we'll be able to reliably handle this case.

Take, for example, the case where an `[]any` slice has multiple different types embedded in it.  We'd have to parse the schema for each row written.

Alternatively, we could parse the schema for the first element and panic/error on subsequent elements which don't match that schema, for better performance.

Personally, I'd prefer to error out at initialization unless there's a compelling use case for lazily parsing the schema from the first element of a slice of `[]any`.

We can always add that behavior in later and remove the error, but we can't add the behavior of parsing the first element's schema and remove that later as that would be a major breaking change.

**Comment by BlakeOrth** [comment]
> Personally, I'd prefer to error out at initialization unless there's a compelling use case for lazily parsing the schema from the first element of a slice of []any.

This seems like a good solution to me. To be entirely clear here, this isn't actually part of a use case I have. I happened to run into this and my general line of thinking is "nobody should ever panic on a nil dereference because we can check for those and error." In the spirit of "fail fast" simply returning an error at initialization for this case seems sufficient.

**Comment by abraithwaite** [comment]
Thanks for the report!
