### ISSUE TITLE
Reading only specific rows, based on match in one column

### ISSUE THREAD

**Issue by berupp** [segmentio/parquet-go#359]
Hi,

I am trying to implement the following logic, but I am a bit lost regarding the APIs I should be using to do this efficiently.

1) I want to read through an ID column, page by page 
2) If I find a specific ID in that column, I want to read the entire row associated with it

It is clear to me how to 1). 

When I have a match I am using 

```	
        rowReader := parquet2.NewRowGroupRowReader(rg)
	defer func() {
		if err := rowReader.Close(); err != nil {
			logger.App.Errorf("error closing row group reader: %s", err.Error())
		}
	}()
        // Skip to row of interest
	if err := rowReader.SeekToRow(int64(position)); err != nil {
		logger.App.Errorf("error seeking to position %d row group reader: %s", position, err.Error())

	}
        //Read just one row
	rowBuf := make([]parquet2.Row, 1) 
	readRows, err := rowReader.ReadRows(rowBuf)
```

So far so good. But my parquet file has some nesting. And the data in rowBuf is flattened, so I am having trouble to understand how to properly correlate my columns to the values in `rowBuf`. 

Any advice how to efficiently implement my use case using this library? I feel I might not be using the correct approach here.

Thank you!

**Comment by achille-roussel** [comment]
Hello @berupp 

The intent is for the `parquet.Row` to a be low-level API focused on offering a high performance mechanism for reading and writing rows, which is why the values are flattened.

To decode the content of a `parquet.Row` into a Go struct value, you may use a `parquet.Schema` (e.g. from the file that you are reading) and call the `Deconstruct` method. Alternatively, if you use a `parquet.Reader` or `parquet.GenericReader`, this decoding can be done automatically when reading rows off the underlying file.

Let me know if the answer was useful!

**Comment by abraithwaite** [comment]
I think if I understand correctly that @berupp is trying to determine the most efficient way to read a single row out of a sorted parquet file given a column value.

We have `Find` to find the page index number given a column index and column value.  With that, we can load the page containing the column value, but not the whole row.

We have `SeekToRow` to seek to a given row index.

But as far as I can tell, we have no way to determine the row index given a column value.  I think that sounds reasonable, but I'm not sure if it's possible today as I'm not familiar enough with the implementation yet.

Lemme know if this clarified things for anybody.

**Comment by achille-roussel** [comment]
Thanks @abraithwaite, I had partially understood the question.

Using `SeekToRow` is the right approach, but maybe the application should use two readers:

* the first reader only decodes the column(s) to filter on, keeping track of the current row index
* each time there is a match, the second reader is positioned on the current row using `SeekToRow` and the application reads the entire row

@berupp do you think this approach would work for your use case?

**Comment by berupp** [comment]
Thank you @achille-roussel 
I did in fact use two readers. The first reader is paging through row groups, only looking at a specific column. 

One I get a hit in that column, I use a `NewRowGroupRowReader` to call `SeekToRow` and `ReadRows`, as outlined in the snippet above. Now I have the `[]Value` representing the row, but flattened. Meaning that if I have multiple nested columns, or in my case, list columns, with arbitrary entries, it get hard to populate a struct from it.

I ended up using the definition and repetition levels on the `Value`, to determine the appropriate columns for it. Nesting in my case is limited to list columns, so it wasn't too much trouble. 

It would be nice to have a convenience method on the `RowGroupRowReader` that reads into an annotated struct, similar to the high level API. 

But my question is resolved, by using repetition and definition levels available on the `Value`s

**Comment by achille-roussel** [comment]
> It would be nice to have a convenience method on the RowGroupRowReader that reads into an annotated struct, similar to the high level API.

I agree with this, supporting somewhat low-level query mechanisms that would perform filtering/selection internally (predicate push down?) would be a useful addition to the library 👍

**Comment by abraithwaite** [comment]
> 
> It would be nice to have a convenience method on the `RowGroupRowReader` that reads into an annotated struct, similar to the high level API.
>

For my own understanding, does this not work?

```
        // Skip to row of interest
	if err := rowReader.SeekToRow(int64(position)); err != nil {
		logger.App.Errorf("error seeking to position %d row group reader: %s", position, err.Error())

	}
        //Read just one row
        val := MyStruct{}
        err = rowReader.Read(&val)
```
