### ISSUE TITLE
LogicalType is nil when is Decimal

### ISSUE THREAD

**Issue by senekis** [segmentio/parquet-go#365]
Using a parquet [file](https://parquet-examples.s3.us-east-2.amazonaws.com/decimal.snappy.parquet) with the following schema:

```
message schema {
  optional int32 int32_decimal (DECIMAL(9, 0));
  optional int32 int32_decimal_s2 (DECIMAL(9, 2));
  optional int64 int64_decimal (DECIMAL(12, 0));
  optional int64 int64_decimal_s2 (DECIMAL(12, 2));
  optional fixed_len_byte_array(16) decimal_s0 (DECIMAL(38, 0));
  optional fixed_len_byte_array(16) decimal_s2 (DECIMAL(38, 2));
}
```

When the following code that prints the PhysicalType and LogicalType for each Field is run:
```go
parquetFile, err := parquet.OpenFile(reader, metadata.Size)
if err != nil {
	return err
}

for _, field := range parquetFile.Schema().Fields() {
	dataType := field.Type().PhysicalType().String()

	if field.Type().LogicalType() != nil {
		dataType += ":" + field.Type().LogicalType().String()
	}
	
	fmt.Println(dataType)
}
```

it is expected to get:
```
INT32:DECIMAL(9,0)
INT32:DECIMAL(9,2)
INT64:DECIMAL(12,0)
INT64:DECIMAL(12,2)
FIXED_LEN_BYTE_ARRAY:DECIMAL(38,0)
FIXED_LEN_BYTE_ARRAY:DECIMAL(38,2)
```

But I got:
```
INT32
INT32
INT64
INT64
FIXED_LEN_BYTE_ARRAY
FIXED_LEN_BYTE_ARRAY
```

**Comment by achille-roussel** [comment]
Hello @senekis, thanks for reporting and providing a file that exhibits the issue! We will look into the reason why this is happening 👍

**Comment by achille-roussel** [comment]
Actually, it appears that I do not have permissions to read the file you linked. Would you be able to upload it to the Github issue?

**Comment by achille-roussel** [comment]
Hello @senekis 

Just a friendly ping in case you have a few spare cycles to provide a copy of the file.

**Comment by senekis** [comment]
Hi @achille-roussel, sorry for the late response, I 'm on vacation..

I changed the permission to the file, you should be able to see it now.

**Comment by lmarburger** [comment]
@senekis Thanks for reporting this bug! Here's the schema I see in the file you posted:

```message schema {
  optional int32 int32_decimal (DECIMAL(9,0));
  optional int32 int32_decimal_s2 (DECIMAL(9,2));
  optional int64 int64_decimal (DECIMAL(12,0));
  optional int64 int64_decimal_s2 (DECIMAL(12,2));
  optional fixed_len_byte_array(16) decimal_s0 (DECIMAL(38,0));
  optional fixed_len_byte_array(16) decimal_s2 (DECIMAL(38,2));
  required int64 timestamp_millis (TIMESTAMP(MILLIS,false));
}
```

and here's what I see running your code after merging #406:

```
INT32:DECIMAL(0,9)
INT32:DECIMAL(2,9)
INT64:DECIMAL(0,12)
INT64:DECIMAL(2,12)
FIXED_LEN_BYTE_ARRAY:DECIMAL(0,38)
FIXED_LEN_BYTE_ARRAY:DECIMAL(2,38)
INT64:TIMESTAMP(isAdjustedToUTC=false,unit=MILLIS)
```

Sadly, it seems that `parquet-go`'s string representation of `DECIMAL` (scale, precision) [is opposite of `parquet-cli` (precision, scale)](https://github.com/apache/parquet-mr/blob/d057b39d93014fe40f5067ee4a33621e65c91552/parquet-column/src/test/java/org/apache/parquet/parser/TestParquetParser.java#L231-L242) which is what I'm using to print the schema above. Regardless, this should be fixed.

**Comment by achille-roussel** [comment]
> Sadly, it seems that parquet-go's string representation of DECIMAL (scale, precision) [is opposite of parquet-cli (precision, scale)](https://github.com/apache/parquet-mr/blob/d057b39d93014fe40f5067ee4a33621e65c91552/parquet-column/src/test/java/org/apache/parquet/parser/TestParquetParser.java#L231-L242) which is what I'm using to print the schema above. Regardless, this should be fixed.

@lmarburger I haven't found any formal specification of the string representation of parquet schemas, but this seems worth changing to align with parquet-cli?

The thrift fields are ordered with [scale first and precision second](https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L245-L256), but if the convention is the opposite for human-readable formats then let's align?

**Comment by lmarburger** [comment]
I have no problem either way. It was strange looking through the parquet-cli code and [seeing all references as (scale, precision)](https://github.com/apache/parquet-mr/blob/d057b39d93014fe40f5067ee4a33621e65c91552/parquet-format-structures/src/main/java/org/apache/parquet/format/LogicalTypes.java#L31-L33) and then [printed in reverse order](https://github.com/apache/parquet-mr/blob/d057b39d93014fe40f5067ee4a33621e65c91552/parquet-column/src/test/java/org/apache/parquet/parser/TestParquetParser.java#L249-L265). Changed in #407.
