### ISSUE TITLE
Missing data page header

### ISSUE THREAD

**Issue by RJKeevil** [segmentio/parquet-go#374]
Hi, I am writing a parquet by creating a new writer
`parquet.NewGenericWriter[structs.JsonParquet](f, parquet.SchemaOf(new(structs.JsonParquet)))`
calling write multiple times (batches of 1000 rows), then closing it with writer.Close().  The file is populated with data, but if i try to open it in a parquet viewer i get the error "column 'json' is missing data page header, file is corrupt".  I am following the examples in the docs and tests, I can't see what I have missed.

**Comment by achille-roussel** [comment]
Hello @RJKeevil and thanks for reporting the issue.

Would you be able to share a code snippet that reproduces the issue, or a copy of the file that triggers it?

**Comment by RJKeevil** [comment]
Hi @achille-roussel, this triggers the problem for me.
`package main

import (
	"github.com/segmentio/parquet-go"
	"os"
)

func main() {

	type JsonParquet struct {
		Json string `parquet:"json"`
	}

	f, _ := os.Create("/mnt/e/data/results.parquet")

	parquetWriter := parquet.NewGenericWriter[JsonParquet](f, parquet.SchemaOf(new(JsonParquet)))
	closeFunc := func() {
		parquetWriter.Close()
		f.Close()
	}
	defer closeFunc()

	for i := 1; i < 1000; i++ {
		var parquetBuffer []JsonParquet
		for j := 1; j < 1000; j++ {
			parquetBuffer = append(parquetBuffer, JsonParquet{Json: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"})
		}
		parquetWriter.Write(parquetBuffer)
	}
}
`

**Comment by achille-roussel** [comment]
I ran the program you provided and the file appears to be readable by the standard `parquet-tools` program:

```
$ parquet-tools schema results.parquet
message JsonParquet {
  required binary json (STRING);
}
```
```
$ parquet-tools meta results.parquet
file:        file:/private/tmp/test/results.parquet
creator:     github.com/segmentio/parquet-go version 0.0.0(build acc0bae1e2e0)

file schema: JsonParquet
--------------------------------------------------------------------------------
json:        REQUIRED BINARY L:STRING R:0 D:0

row group 1: RC:998001 TS:215612542 OFFSET:4
--------------------------------------------------------------------------------
json:         BINARY UNCOMPRESSED DO:0 FPO:4 SZ:215612542/215612542/1.00 VC:998001 ENC:DELTA_LENGTH_BYTE_ARRAY ST:[no stats for this column]
```
```
$ parquet-tools dump results.parquet
row group 0
--------------------------------------------------------------------------------
json:  BINARY UNCOMPRESSED DO:0 FPO:4 SZ:215612542/215612542/1.00 VC:998001 [more]...

    json TV=998001 RL=0 DL=0
    ----------------------------------------------------------------------------
    page 0:   DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 1:   DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 2:   DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 3:   DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 4:   DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 5:   DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 6:   DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 7:   DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 8:   DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 9:   DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 10:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 11:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 12:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 13:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 14:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 15:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 16:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 17:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 18:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 19:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 20:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 21:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 22:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 23:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 24:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 25:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 26:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 27:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 28:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 29:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 30:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 31:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 32:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 33:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 34:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 35:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973
    page 36:  DLE:RLE RLE:RLE VLE:DELTA_LENGTH_BYTE_ARRAY ST:[no stats [more]... VC:26973

BINARY json
--------------------------------------------------------------------------------
*** row group 1 of 1, values 1 to 998001 ***
...
```

Would you be able to point me at the program you are attempting to open the file with?

**Comment by achille-roussel** [comment]
Actually the program I am referring to is the historical `parquet-tools` from the `parquet-mr` repository, which has been renamed to [`parquet-cli`](https://github.com/apache/parquet-mr/tree/master/parquet-cli) since.

Something that I am wondering about is whether the ParquetViewer program support some of the default format and encoding choices we made for parquet-go. For example, we use DELTA_LENGTH_BYTE_ARRAY by default to encode BYTE_ARRAY columns (as documented in the parquet spec), I know some libraries have issues with this encoding since it was introduced later in the parquet format. The .Net library that ParquetViewer is built upon does not seem to have implemented this encoding either? https://github.com/aloneguid/parquet-dotnet/search?q=%27DELTA_LENGTH_BYTE_ARRAY%27

Something you could try is changing the encoding to PLAIN which might increase compatibility with other parquet libraries:
```go
type JsonParquet struct {
	Json string `parquet:"json,plain"`
}
```

**Comment by RJKeevil** [comment]
Thanks @achille-roussel, in honest answer I dont really need to use these utilities, as long as the file is readable in Spark (which I just tested works fine).  I was using them as a quick test to check if the parquet was valid, as they did work with the previous library i was using to write parquet.  As it seems these tools are to blame then this is a non-issue.   Thanks for the support!
