### ISSUE TITLE
Convert parquet.Value to a Go value

### ISSUE THREAD

**Issue by tschaub** [segmentio/parquet-go#390]
I see the [`parquet.ValueOf` function](https://pkg.go.dev/github.com/segmentio/parquet-go#ValueOf) that converts a "Go value" into a `parquet.Value`.  Is there a function exported that does the inverse?  I assume this would only work for values corresponding to "leaf nodes" (unsure of the right language).

**Comment by achille-roussel** [comment]
Hello @tschaub, thanks for reaching out!

Some work is being done in https://github.com/segmentio/parquet-go/pull/387 which might be relevant to your question.

Please take a look and feel free to follow up here if you have any feedback!

**Comment by achille-roussel** [comment]
I see, thanks for the details.

I think adding the `parquet.Value.Interface` method you suggested would be a useful addition.

Would you have spare cycles to contribute this change to the package?

**Comment by tschaub** [comment]
I'll see if I can put something together.

**Comment by tschaub** [comment]
I had missed the `Reconstruct` method on a schema.  I'm able to do what I was trying to do with this:

```go
data := map[string]any{}
schema.Reconstruct(&data, row)
```
