### ISSUE TITLE
Build status badge shows failing tests

### ISSUE THREAD

**Issue by tschaub** [segmentio/parquet-go#402]
I was curious if it was intentional that the tests are not run on the default branch.  As it is now, the [build status badge](https://pkg.go.dev/github.com/segmentio/parquet-go#pkg-overview) often shows failing tests since the latest action might be from any PR.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/41094/200447805-33cee94b-10ef-4973-800a-45ef454b65df.png">

I understand there might be a good reason that the tests are not run on `main`.  If not, would a change like this be acceptable: https://github.com/segmentio/parquet-go/compare/main...tschaub:parquet-go:test-main ?

**Comment by kevinburkesegment** [comment]
![19375577028_018dd0a6c9_b](https://user-images.githubusercontent.com/96151026/200480648-b30310d5-8cc3-4606-a2fb-8c6f7879f804.jpg)

**Comment by tschaub** [comment]
@achille-roussel - I opened #403 and left a little more detail there.
