### ISSUE TITLE
Question: How can stats get added to row group columns?

### ISSUE THREAD

**Issue by rcaught** [segmentio/parquet-go#410]
I'm generating files with the generic writer, but when I read the meta data for my generated files, every row group column has `ST:[no stats for this column]`. This I believe will lead to very poor predicate searching, etc in other tools.

Its unclear of the steps I would have to take to have these stats produced. Do I need to run everything through a buffered sort? Or is this simply not supported yet?

**Comment by achille-roussel** [comment]
Hello @rcaught 

parquet-go currently does not generate column stats but this could be added to the library.

We always welcome contributions, would you have time to submit a pull request which adds this feature?
