### ISSUE TITLE
Proposal: Return closer on Rows() api

### ISSUE THREAD

**Issue by thorfour** [segmentio/parquet-go#421]
Right now the `RowGroup` interface has a `Rows() Rows` function that returns an object that is of type `io.Closer`: 
https://github.com/segmentio/parquet-go/blob/0a0fad09d0068ea04b6797e90859ae752b23b2d6/row_group.go#L52-L65

We've found this to be a footgun when developing as it's not obvious that the Rows object is required to be closed and will then leak resources. 

I propose that we change the interface to return an explicit closer function
```go
Rows() (Rows, io.Closer)
```

This way it's explicit when using the API that the object needs to be closed, and most linters will throw an error if the closer function is not handled.

**Comment by achille-roussel** [comment]
Technically the rows are not required to be closed, the program remains correct and the GC eventually reclaims memory.

I'm a bit hesitant to take this approach, what makes `parquet.Rows` different from `*sql.Rows` in the standard `database/sql` package for example?

Would it be possible to create a linter rule maybe which helps detect `io.Closer` values which are not being closed by the application?
